services:
  bot:
    container_name: smoke-bot
    image: ghcr.io/aqyuki/smoke/smoke:v1.0.1
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - smoke-network

networks:
  smoke-network:
