services:
  bot:
    container_name: tubu-bot
    image: ghcr.io/aqyuki/tubu/tubu:1.0.1
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - tubu-network

networks:
  tubu-network:
