services:
  memos:
    container_name: memos
    image: neosmemo/memos:0.22.4
    restart: always
    depends_on:
      - db
    ports:
      - 5230:5230
    environment:
      - MEMOS_DRIVER=postgres
    env_file:
      - .env
    volumes:
      - type: bind
        source: /var/deployment/memos/memos
        target: /var/opt/memos
    networks:
      memos-network:
      web-app-network:
  db:
    container_name: memos-db
    image: postgres:16.4
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/deployment/memos/database
        target: /var/lib/postgresql/data
    env_file:
      - .env
    networks:
      memos-network:

networks:
  memos-network:
  web-app-network:
    external: true
