services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2024-08-03T04-33-23Z
    ports:
      - "9000:9000" # API port
      - "9001:9001" # web console
    env_file:
      - .env
    command: "server /export --address :9000 --console-address :9001"
    volumes:
      - "/var/deployment/minio:/export"
    networks:
      web-app-network:
        ipv4_address: 172.23.10.1

networks:
  web-app-network:
    external: true
