services:
  vaultwarden:
    image: vaultwarden/server:1.31.0
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      SIGNUPS_ALLOWED: "false"
    volumes:
      - /var/deployment/vaultwarden:/data # the path before the : can be changed
    ports:
      - 11000:80
