services:
  vaultwarden:
    image: vaultwarden/server:1.31.0
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      # DOMAIN: "https://vaultwarden.example.com"  # required when using a reverse proxy; your domain; vaultwarden needs to know it's https to work properly with attachments
      SIGNUPS_ALLOWED: "true" # Deactivate this with "false" after you have created your account so that no strangers can register
    volumes:
      - /var/deployment/vaultwarden:/data # the path before the : can be changed
    ports:
      - 11000:80
